#pragma once

#define ONESHOT_TAP_TOGGLE 3
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define TAPPING_TERM 200
#define FLOW_TAP_TERM 150
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD
#define SPECULATIVE_HOLD

#define EXTRA_SHORT_COMBOS
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_TERM 40
#define COMBO_STRICT_TIMER
