# From vendor rules
VIA_ENABLE = yes
ENCODER_MAP_ENABLE = yes

TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
COMBO_ENABLE = yes
LTO_ENABLE = yes

